version: "2"

#/opt/bitnami/kafka/bin/kafka-topics.sh --describe --bootstrap-server kafka-1:9092

services:
  kafka-1:
    image: docker.io/bitnami/kafka:3.6
    environment:
      # KRaft settings
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka-1:9093,1@kafka-2:9093
      - KAFKA_KRAFT_CLUSTER_ID=p8fFEbKGQ22B6M_Da_vCBw
      # Listeners
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=2
      - KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=2
      - KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR=2

  kafka-2:
    image: docker.io/bitnami/kafka:3.6
    environment:
      # KRaft settings
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka-1:9093,1@kafka-2:9093
      - KAFKA_KRAFT_CLUSTER_ID=p8fFEbKGQ22B6M_Da_vCBw
      # Listeners
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=2
      - KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=2
      - KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR=2

  producer-1:
    image: bistik/example-service:custom-jre-producer
    environment:
      - SPRING_APPLICATION_NAME="Producer-1"
      - SPRING_KAFKA_BOOTSTRAP-SERVERS=kafka-1:9092,kafka-2:9092
    depends_on:
      kafka-1:
        condition: service_started
      kafka-2:
        condition: service_started

  producer-2:
    image: bistik/example-service:custom-jre-producer
    environment:
      - SPRING_APPLICATION_NAME="Producer-2"
      - SPRING_KAFKA_BOOTSTRAP-SERVERS=kafka-1:9092,kafka-2:9092
    depends_on:
      kafka-1:
        condition: service_started
      kafka-2:
        condition: service_started

  producer-3:
    image: bistik/example-service:custom-jre-producer
    environment:
      - SPRING_APPLICATION_NAME="Producer-3"
      - SPRING_KAFKA_BOOTSTRAP-SERVERS=kafka-1:9092,kafka-2:9092
    depends_on:
      kafka-1:
        condition: service_started
      kafka-2:
        condition: service_started

  consumer-1:
    image: bistik/example-service:custom-jre-consumer
    environment:
      - SPRING_APPLICATION_NAME="Consumer-1"
      - SPRING_KAFKA_BOOTSTRAP-SERVERS=kafka-1:9092,kafka-2:9092
      - SPRING_KAFKA_CONSUMER_GROUP-ID="single-group"
    depends_on:
      kafka-1:
        condition: service_started
      kafka-2:
        condition: service_started

  consumer-2:
    image: bistik/example-service:custom-jre-consumer
    environment:
      - SPRING_APPLICATION_NAME="Consumer-2"
      - SPRING_KAFKA_BOOTSTRAP-SERVERS=kafka-1:9092,kafka-2:9092
      - SPRING_KAFKA_CONSUMER_GROUP-ID="single-group"
    depends_on:
      kafka-1:
        condition: service_started
      kafka-2:
        condition: service_started
